
Az újabb libxcb-s X környezetben szükséges az XInitThreads()
hívás, noha a korábbi man szerint az nem kellene:

    It is only necessary to call this function if multiple threads 
    might use Xlib concurrently. If all calls to Xlib functions are 
    protected by some other access mechanism (for example, a mutual 
    exclusion lock in a toolkit or through explicit client programming), 
    Xlib thread initialization is not required. It is recommended that 
    single-threaded programs not call this function. 

XInitThreads() nélkül ez a hiba keletkezik:

terminal.exe: ../../src/xcb_lock.c:32: _XCBUnlockDisplay: Assertion `dpy->xcb->partial_request == 0' failed.

A z-ben jobbra-balra mozgatva a kurzort, elég hamar kijön a hiba.
Szerintem ez a libxcb implementáció belső hibája.
